version: "3"
services: 
  postgres: 
    image: postgres:14-alpine
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=simple_bank
    ports: 
      - 5432:5432
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
  api: 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports: 
      - 8080:8080
      - 9090:9090
    environment: 
      - DB_SOURCE=postgres://root:root@postgres:5432/simple_bank?sslmode=disable
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - postgres
      - redis
    entrypoint: sleep infinity
        #entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
        #command: [ "/app/main" ]

  
