name: Deploy to production

on:
  push:
    branches: [ "master" ]

jobs:

  deploy:
    name: Build image
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::431062523786:role/github-action-role 
          aws-region: ap-southeast-1

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.25.2
        id: install

      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Check out code
        uses: actions/checkout@v3

      - name: Load secrets from AWS secret manager and save to app.env
        run: aws secretsmanager get-secret-value --secret-id simple_bank --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > app.env

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: simplebank
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REPOSITORY:latest .
          docker push $REGISTRY/$REPOSITORY

          #      - name: Update kube config
          #        run: aws eks update-kubeconfig --name simple-bank --region ap-southeast-1
          #
          #      - name: Deploy image to AWS EKS
          #        run: |
          #          kubectl apply -f eks/aws-auth.yaml
          #          kubectl apply -f eks/deployment.yaml
          #          kubectl apply -f eks/service.yaml
          #          kubectl apply -f eks/issuer.yaml
          #          kubectl apply -f eks/ingress.yaml
